### ISSUE TITLE
VideoPlayer.GetTexture() and VideoPlayer.Stop() crash in UWP Projects

### ISSUE THREAD

**Issue by xlebec** [MonoGame/MonoGame#5920]
Occurs when running UWP project on Xbox and Windows. Haven't tested other platforms. Non-UWP Windows project executes these methods without issue. Error messages below.

**VideoPlayer.GetTexture()**
Exception thrown: 'SharpDX.SharpDXException' in SharpDX.dll
An exception of type 'SharpDX.SharpDXException' occurred in SharpDX.dll but was not handled in user code
HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

**VideoPlayer.Stop()**
An exception of type 'SharpDX.SharpDXException' occurred in SharpDX.dll but was not handled in user code
HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

**Comment by Jjagg** [comment]
Are you using a develop version of MG?

**Comment by xlebec** [comment]
I'm using version 3.6.0.1625. If I recall correctly I installed it through the link on http://www.monogame.net/2017/03/01/monogame-3-6/ so I don't believe it's a develop version.

**Comment by willmotil** [comment]
I found this to be a common problem especially the faster the video frame rate is for the video.
I got videos that would crash with the texture error to work... by running them thru ffmpeg and slowing down the frame rate and reducing the quality.

**Comment by dayofbrian** [comment]
I've hit this issue also, the audio plays, but trying to retrieve the texture with the GetTexture() method crashes the app.

**Comment by alexus37** [comment]
Is there a workaround?

**Comment by BrianBergh** [comment]
I also have this issue. It works fine in 3.6.0.1625, but when using the latest release (or development branch), i get an object not set to an instance exception when getting the texture (getTexture()) - This is a show stopper for my project, and 3.7 fixes some other issues that are show-stopper for my project in 3.6 - Is MonoGame dying, or are the list of high-priority issues just so long, since it isn't fixed? (I'd gladly contribute, but i don't think that i have the skills) - Don't get me wrong, i LOVE monogame, but if critical bugs like this aren't fixed fast, i will have to consider using something else for my projects.

**Comment by Belkaar** [comment]
I think I found the cause:

Changing VideoPlayer.WME.cs:83
from
_mediaEngine.TransferVideoFrame(_lastFrame._texture, null, region, null);
to
_mediaEngine.TransferVideoFrame(_lastFrame.GetTexture(), null, region, null);

Fixes the Problem for me.

Two sideeffects / still present bugs:
* you need to manually dispose of the returned Texture2D after drawing or my app uses 2GB of memory after 10 seconds
* I need to wait 500 ms or a couple of updates or I will get exception 0xC00D4E26 (MF_E_NO_VIDEO_SAMPLE_AVAILABLE)

I'm not sure why there is a new Texture created every call, but the Exception should be caught and a Null Texture returned, like the comment says.

**Comment by Jjagg** [comment]
@Belkaar that is definitely not the right fix.

**Comment by BrianBergh** [comment]
In version 3.6, you also need to dispose the texture2d you get from VideoPlayer.GetTexture(), or you will end up using all memory on your gfx card in matter of seconds. That was not the case in XNA 4, don't know why there is this difference, but its not a huge issue to me, i just call videoTexture.dispose() when im done with the drawing.

By the way: in addition to the title "VideoPlayer.Stop()" crash the player... 

1. "VideoPlayer.Resume()" also crash the player, after calling "VideoPlayer.Pause()"...  
2. "VideoPlayer.IsLooping" throws an "Not Implemented Exception"
3. When the video ends, the MG framework crashes (and stops rendering) without any exception.
4. And....
I see huge frame-drops in my 3d scene when the video player is running. (even if i don't use GetTexture() - In other words, the VideoPlayer is just playing, but im not using it.) The scene i render, can easily render with 5000 fps on my pc, when disabling vsync and fixedtime (with VideoPlayer running, and GetTexture() getting called every frame), but still i get frame-drops (lags spikes) as soon the player is "playing", if i stop the player, everything runs smooth.

Seems that VideoPlayer could use some serious attention.

Again, i'd be happy to contribute - but i have nothing to contribute with (other than feedback and test)

**Comment by willmotil** [comment]
Yea it was messed up when before and it looks like since i haven't messed with it in so long my old videoplayer app throws errors now. 

This is the ffmpeg command i think i used to use for file conversion but doesn't look like its any good anymore.

FFmpeg ExecuteCommand
command:

ffmpeg -y -i "C:\Users\Me\Documents\Video\test.mp4" -c:v libx264 -profile:v main -level:v 3.0 -ab 84k -vf fps=32 -s 450x300 -c:a copy "C:\Users\Me\Documents\Video\Output\test.mp4"

** done

You can take a look at this. https://slhck.info/video/2017/03/01/rate-control.html

I really don't want to get sidetracked but maybe ill rebuild this old test app its really just a mess.
Maybe i will though ya the video player is sort of ugly in use the last time it did work it was doing goffy crap.

**Comment by jrett** [comment]
Is this on the list to be fixed any time soon? I've been waiting for a fix for 2 years now.

**Comment by vrgamestudio** [comment]
Hello, April 28th 2023 here and still getting the same issue in UWP DirectX. Same code works fine in Windows DX but then the DX code uses VideoPlayer.WMS, UWP uses VideoPlayer.WME.

I've noticed that...

First time Draw a texture is returned that appears to be Blank but it's not null and can be drawn without error (but there's nothing there).

Second time round is when the exceptions start...

If I Dispose the Texture2D after drawing then I get the error message above but if I don't I get a slightly different: **A video sample is not currently queued on a stream that is required for mixing.**

```
VideoPlayer.WME.cs, Line 83:

This exception was originally thrown at this call stack:
    SharpDX.Result.CheckError()
    SharpDX.MediaFoundation.MediaEngine.TransferVideoFrame(SharpDX.ComObject, SharpDX.MediaFoundation.VideoNormalizedRect?, SharpDX.Mathematics.Interop.RawRectangle, SharpDX.Mathematics.Interop.RawColorBGRA?)
    Microsoft.Xna.Framework.Media.VideoPlayer.PlatformGetTexture() in VideoPlayer.WME.cs
    Microsoft.Xna.Framework.Media.VideoPlayer.GetTexture() in VideoPlayer.cs
    Mono.Shared.Game1.Draw(Microsoft.Xna.Framework.GameTime) in Game1.cs

 

HRESULT: [0xC00D4E26], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: A video sample is not currently queued on a stream that is required for mixing.


at SharpDX.Result.CheckError()
   at SharpDX.MediaFoundation.MediaEngine.TransferVideoFrame(ComObject dstSurfRef, Nullable`1 srcRef, RawRectangle dstRef, Nullable`1 borderClrRef)
   at Microsoft.Xna.Framework.Media.VideoPlayer.PlatformGetTexture()
   at Microsoft.Xna.Framework.Media.VideoPlayer.GetTexture()
   at Mono.Shared.Game1.Draw(GameTime gameTime) in D:\Projects\Tests\MonoGamePlayVideo\Mono.Shared\Game1.cs:line 67
```

**Comment by vrgamestudio** [comment]
Some more info if it may help someone as a workaround of sorts:

UWP Xaml apps can take advantage of Xaml UI components and use those to play video in a Xaml layer's "swapChainPanel" (which is created as default by the MonoGame UWP Xaml Template in the GamePage.xaml page and assigned to the GraphicsDeviceManager property of the same name). Therefore you could play a fullscreen video something like this in a Game1.LoadContent() method:

```
MediaElement newElement = new MediaElement();
newElement.Source = new Uri("ms-appx:///Content/com.oculus.vrshell-20200304-030407.mp4");
_graphics.SwapChainPanel.Children.Add(newElement);
newElement.Play();
```
Created by default, note the **SwapChainPanel**:
```
<Page
    x:Class="PlayVideoUWPCore.GamePage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:UwpGame"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <SwapChainPanel x:Name="swapChainPanel"/>
</Page>
```

It's also worth noting that the mp4 original video file seems to be preserved and copied over from the build process, the XNB file just acting as a kind of wrapper. So you could maybe write a component (a DrawableGameComponent perhaps) that might act as a Shim for both types of behaviour. Unfortunately UWP Core games with no Xaml throw exceptions if you try to do mad things like create SwapChainPanels dynamically in code so it seems to be no dice for Core Apps I'm afraid.

**Comment by mrhelmut** [comment]
Cleaning this as UWP is getting deprecated #8406
