### ISSUE TITLE
Unable to create new solution from template

### ISSUE THREAD

**Issue by Revolt64** [MonoGame/MonoGame#6504]
#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- macOS 10.13.6

#### What MonoGame platform are you using:

- DesktopGL

When attempting to create a new solution via the MonoGame templates (MonoGame Mac Application) in the latest version of Visual Studio for Mac, I get the following error:

![new_project_and_visual_studio_community_2017_for_mac-2](https://user-images.githubusercontent.com/42483196/47102397-8cf81100-d234-11e8-91f5-e5251ab0e099.jpg)

![new_project_and_visual_studio_community_2017_for_mac](https://user-images.githubusercontent.com/42483196/47102023-8a48ec00-d233-11e8-9d51-e76888b743cb.jpg)

EDIT: I resolved the issue by removing the Monogame extension for VS for Mac and installing it from the NuGet gallery instead.

Thanks

**Comment by Apostolique** [comment]
Based on your edit, I take it this issue is solved?

**Comment by Revolt64** [comment]
Yep!

**Comment by Jjagg** [comment]
We should make sure the template that comes with the installer doesn't have any issues so it just works out of the box.

**Comment by Revolt64** [comment]
If it helps..

I installed MonoGame first, then I installed Visual Studio for Mac after. 
There were naturally no templates available when I initially opened VS for Mac.

So then I installed MonoGame again (dirty install) then the templates were shown in VS for Mac. I had the issue described in the OP however.

Installing MonoGame again (tried a few times) didn't resolve the issue.
Hope this helps.

**Comment by harry-cpp** [comment]
Fixed in develop.
