### ISSUE TITLE
GamePad Y-Button Not Registering

### ISSUE THREAD

**Issue by Meowmaritus** [MonoGame/MonoGame#6517]
The following returns false regardless of whether you're pressing the Y-button:
```cs
GamePad.GetState(0).IsButtonDown(Buttons.Y)
```

This always returns false as well:
```cs
(GamePad.GetState(0).Buttons.Y == ButtonState.Pressed) 
```

I've tested with multiple XInput controllers which have working Y-buttons that register in other applications. All buttons other than Y work.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7, 3.8.0.93

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by BenMakesGames** [comment]
I'm experiencing this problem as well. I have the same version of MonoGame (3.7.0.1708).

**Comment by dmanning23** [comment]
I've been digging into this problem, and yeah there is an open SharpDX ticket for it:

https://github.com/sharpdx/SharpDX/issues/961

**Comment by Jjagg** [comment]
@dmanning23 
Looks like the proposed pull request in that issue was merged, so the issue should be fixed in latest SharpDX. We really should upgrade.

**Comment by dmanning23** [comment]
Yeah I dug a bit deeper, becase what's in that PR isn't what is on the SharpDX master branch...
Looks like the PR was merged, but it was incorrect and another issue was opened:
https://github.com/sharpdx/SharpDX/issues/987
and then another PR was created:
https://github.com/sharpdx/SharpDX/pull/1025

If I update the SharpDX.XInput nuget package to the latest 4.2.0 version though, I still have this Y button issue in my MonoGame projects. It should've been fixed since the 4.0.1 release:
https://github.com/sharpdx/SharpDX/compare/v4.0.1...master
