### ISSUE TITLE
Content Pipeline Tool crashes when adding an assembly that references another assembly

### ISSUE THREAD

**Issue by BrettStory** [MonoGame/MonoGame#6676]
#### What version of MonoGame does the bug occur on:
- MonoGame 3.7, 3.7.1, 3.8 (development branch)

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:
- DesktopGL

I have an assembly that uses Newtonsoft.Json for a custom importer. When I attempt to add the assembly as a reference in the content pipeline tool, I get a crash with the following exception:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
```

If I edit the Content.mgcb file manually to add the reference, I simply get an error window that says, "Content.mgcb: Failed to open the project due to an unknown error."

This previously worked under the same conditions with MonoGame 3.6. I'm currently using a relative path to my assembly. The NewtonSoft.Json assembly is in the same folder. I have also tried absolute paths.

**Comment by BrettStory** [comment]
After working with the source code a bit, this appears to be related to commit https://github.com/MonoGame/MonoGame/commit/9d7d5b7872fd6584ecf971572f12e5811536ac60

The switch from Assembly.LoadFrom to Assembly.Load has stopped the pipeline tool from loading the second-hand reference. Is there some other way I should be handling this situation? I feel as though I have a fairly simple use case that surely someone else would have run into (I have not found any issues similar to my own on this repository).

**Comment by BrettStory** [comment]
Part of the issue appears to be that when the CurrentDomain_AssemblyResolve event is fired to find NewtonSoft.Json.dll, _currentAssemblyDirectory is null and therefore it never gets loaded. CurrentDomain_AssemblyResolve is called when an instance of a custom processor is created with Activator.CreateInstance(...).

**Comment by nkast** [comment]
@BrettStory 

>>  Is there some other way I should be handling this situation? I feel as though I have a fairly simple use >>  case that surely someone else would have run into

Another way is to use shadow copy. 
https://github.com/MonoGame/MonoGame/issues/5769#issuecomment-308153068

**Comment by BrettStory** [comment]
> @BrettStory
> 
> > > Is there some other way I should be handling this situation? I feel as though I have a fairly simple use >>  case that surely someone else would have run into
> 
> Another way is to use shadow copy.
> [#5769 (comment)](https://github.com/MonoGame/MonoGame/issues/5769#issuecomment-308153068)

I'm not sure I completely follow. My issue isn't that the files are in use, it's that the pipeline tool has no way of knowing where NewtonSoft.Json.dll would be (which my importer DLL references), even though it's in the same folder as my importer DLL. If you look at my pull request (https://github.com/MonoGame/MonoGame/pull/6678), you'll see that when it comes to resolving an assembly, the current assembly path is always set to null, so it has no idea where to find referenced assemblies.

**Comment by nkast** [comment]
I meant that ShadowCopy is an alternative to the use of Assembly.Load(). The framework handles loading 
and resolving references automatically. It implies that you'd have to load the assembly in a separate AppDomain and load the Processor properties through aProxy.

**Comment by BrettStory** [comment]
Ah okay, that makes more sense. I misunderstood what you were referring to.
My bad.

**Comment by QuinnBast** [comment]
Is there a workaround to this? This is pretty critical to any development in Monogame 3.7 and 3.7.1 if the pipeline is failing when any dlls are added. You literally can't start working on a MonoGame project if you want to import additional libraries that depend on pipeline references. A few examples of this are Monogame.Extended.Gui and GeonBit.UI, both which are unusable with MG3.7 and MG3.7.1 because of this bug.

It's effecting a ton of libraries that I've tried so far, all of which are getting the same error when I try to import them into the content pipeline:

```
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at MonoGame.Tools.Pipeline.PipelineTypes.ResolveAssemblies(IEnumerable`1 assemblyPaths)
   at MonoGame.Tools.Pipeline.PipelineTypes.Load(PipelineProject project)
   at MonoGame.Tools.Pipeline.PipelineController.ResolveTypes()
   at MonoGame.Tools.Pipeline.PipelineController.OnReferencesModified()
   at MonoGame.Tools.Pipeline.CellRefs.Edit(PixelLayout control)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at MonoGame.Tools.Pipeline.Program.Main(String[] args)
```

The most related error/issue seems to be this one:
https://github.com/MonoGame/MonoGame/issues/5944

I can confirm this is happening in both MacOS and Windows environments in the content pipeline.

But there are TONS of other related errors that seem to have the same issue:
https://github.com/MonoGame/MonoGame/issues/6443
https://github.com/tainicom/Aether.Extras/issues/10
https://github.com/MonoGame/MonoGame/issues/6443
https://github.com/RonenNess/GeonBit.UI/issues/107
http://community.monogame.net/t/pipeline-tool-has-crashed/11697
http://community.monogame.net/t/net-core-3-monogame-extended-content-pipeline/11930
http://community.monogame.net/t/xmlimporter-failure-unable-to-load-one-or-more-of-the-requested-types/9669
https://github.com/MonoGame/MonoGame/issues/6538
https://github.com/MonoGame/MonoGame/pull/6566 -- Same error that was reported fixed here
https://github.com/MonoGame/MonoGame/issues/4166
https://github.com/MonoGame/MonoGame/issues/5924

Praying this gets fixed as I'm sure downgrading to an older version of monogame will break half my code.

**Comment by cra0zy** [comment]
Its fixed in develop.

**Comment by QuinnBast** [comment]
Just installed dev to my machine and has some minor updates required to my code base but once fixed, I tried adding a .dll Reference to the content pipeline and was met with the exact same error as all my linked issues posted above. Definitely not fixed in develop:

I could still reproduce the issues with the following steps which I indicated above (did you try them?)

1. Create a new empty MonoGame project
2. Install Monogame.Extended.Gui NuGet package (Or any other package that requires a pipeline reference).
3. Follow the instructions here to add the reference to the pipeline: Adding a reference to the monogame pipeline
4. Once the reference is added, try removing/readding the reference from the pipeline. The Pipeline will crash.

```
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at MonoGame.Tools.Pipeline.PipelineTypes.ResolveAssemblies(IEnumerable`1 assemblyPaths)
   at MonoGame.Tools.Pipeline.PipelineTypes.Load(PipelineProject project)
   at MonoGame.Tools.Pipeline.PipelineController.ResolveTypes()
   at MonoGame.Tools.Pipeline.PipelineController.OnReferencesModified()
   at MonoGame.Tools.Pipeline.CellRefs.Edit(PixelLayout control)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at MonoGame.Tools.Pipeline.Program.Main(String[] args)
```
