### ISSUE TITLE
[UWP] GamePad might produce NaN stick values

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#7015]
Hello there :)

We recently found out that ```GamPadState.Thumbsticks``` may have ```float.NaN``` values in some circumstances.

We were unable to reproduce it locally with Xbox 360 and Xbox One controllers, but we were getting lots of report from players and could confirm that it comes from thumbsticks.

My assumption is that the aberrant values may come from non-Microsoft branded controllers, like using software such as DS4Windows to emulate XInput controllers.

It would probably cool to add some safe checks to the thumbsticks constructor to make sure that the stick values are within acceptable ranges.

#### What version of MonoGame does the bug occur on:
- Current develop branch

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- Windows Universal

**Comment by harry-cpp** [comment]
I am not sure both how or if we should fix this at all.

For how, what do we set the value if the thing sent by the UWP was something outside of its documented range. Do we try and get the last valid state and send that?

Also should we fix it on MonoGame side at all as the bug is clearly not us but the lib bellow that's causing the problem.

**Comment by mrhelmut** [comment]
If we don't fix it, we should at least document it.
It is also beyond my understanding that the input API of UWP returns out of range values.

**Comment by harry-cpp** [comment]
It shouldn't, the docs say it returns a value between -1f and 1f.

**Comment by tomspilman** [comment]
> It is also beyond my understanding that the input API of UWP returns out of range values.

Well if that is truely where the NaNs are coming from there is not much we can do.  Even if we detect this and avoid the NaN's the controllers still won't work.

We could just add something like:
```
Stick = new Vector2(Stick.X == Stick.X ? Stick.X : 0, Stick.Y == Stick.Y ? Stick.Y : 0);
```
Which just disables the bad inputs.

**Comment by harry-cpp** [comment]
> Which just disables the bad inputs.

But returning 0 as an input is still invalid. The best option would be to return last valid input.

**Comment by mrhelmut** [comment]
I agree, returning the last valid input seems smoother.

**Comment by mrhelmut** [comment]
Cleaning this as UWP is getting deprecated #8406
