### ISSUE TITLE
System.TypeInitializationException: 'The type initializer for 'Sdl' threw an exception.'

### ISSUE THREAD

**Issue by Lancelotbronner** [MonoGame/MonoGame#9047]
### Prerequisites

- [x] I have verified this issue is present in the `develop` branch
- [x] I have searched [open](https://github.com/MonoGame/MonoGame/issues) and [closed](https://github.com/MonoGame/MonoGame/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported.

### MonoGame Version

MonoGame 3.8.4

### Which MonoGame platform are you using?

MonoGame Cross-Platform Desktop Application (mgdesktopgl)

### Operating System

Windows

### Description

Starting from a fresh Monogame template, haven't modified anything and it crashes.
The SDL2 dll is present next to the executable.

I'm using VS 2026 and Windows 11 on arm if that makes any difference.

### Steps to Reproduce

1. Create new project from latest templates
2. Run
3. Crash.

### Expected Behavior

The official templates should at least compile without modifications.

### Resulting Behavior

Crash.

**Comment by ThomasFOG** [comment]
> VS 2026 and Windows 11 on arm if that makes any difference

It makes a big one.

I believe this is fixed for 3.8.5. You can test a preview by using the ```3.8.5-develop.12``` nugets.

**Comment by Lancelotbronner** [comment]
Using `3.8.5-develop.12` I get a different crash, I believe it might be the same but VS doesn't catch it?

Here's the whole output, the debugger does attach but doesn't seem to catch the exceptions.

```
Exception thrown: 'System.DllNotFoundException' in System.Private.CoreLib.dll
Exception thrown: 'System.TypeInitializationException' in MonoGame.Framework.dll
```

**Comment by ThomasFOG** [comment]
Do you happen to have manually replaced the dll yourself? (if so, you shouldn't)

Maybe try to delete the ```bin``` and ```obj``` folders before attempting to rebuild, just to make sure that the correct dll gets in the output folder.

Are you running VS for ARM _and_ .NET for ARM?

**Comment by Lancelotbronner** [comment]
I haven't, still happens after deleting the `bin` and `obj` folders.

I tried with both .NET8 for ARM via the command-line and VS2026's bundled .NET10 and got the same result.

I'm not sure if VS2026 detected Windows for ARM on download or something but it is running properly on an ARM machine so, I would assume so?

**Comment by Lancelotbronner** [comment]
I don't have that issue when running on macOS but it's not a viable workaround (I use Windows-exclusive APIs so it just crashes later with platform exceptions).

**Comment by Lancelotbronner** [comment]
Still happens with `3.8.5.develop-13` on the official release of VS2026. @ThomasFOG

**Comment by dellis1972** [comment]
https://github.com/MonoGame/MonoGame.Library.SDL/releases
https://github.com/MonoGame/MonoGame.Library.OpenAL/releases
These releases ^ have the windows arm64 binaries in the nuget packages
they just havent made it to the nuget.org yet (then we need to bump them in the main repo)

**Comment by JarradBaker** [comment]
Still having this issue with current releaseb

**Comment by Lancelotbronner** [comment]
> they just havent made it to the nuget.org yet (then we need to bump them in the main repo)

When can we expect it to be done? It's still an issue as of `3.8.5-preview.3`.

**Comment by dellis1972** [comment]
@Lancelotbronner 

try adding the following to your main DesktopGL project

```xml
<PackageReference Include="MonoGame.Library.SDL" Version="2.32.10.2" />
<PackageReference Include="MonoGame.Library.OpenAL" Version="1.24.3.4" />
```

This _should_ override what MonoGame currently has with the latest versions of SDL and OpenAL, these contain the win-arm64 runtime binaries.

**Comment by Lancelotbronner** [comment]
Still happens :( same when replacing `PackageVersion` with `PackageReference`.

```xml
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<RollForward>Major</RollForward>
		<PublishReadyToRun>false</PublishReadyToRun>
		<TieredCompilation>false</TieredCompilation>
		<PublishSingleFile>false</PublishSingleFile>
	</PropertyGroup>
	<PropertyGroup>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	</PropertyGroup>
	<PropertyGroup>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ApplicationIcon>app.ico</ApplicationIcon>
	</PropertyGroup>
	<ItemGroup>
		<EmbeddedResource Include="app.ico">
			<LogicalName>Icon.ico</LogicalName>
		</EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.5-preview.3" />
		<PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.5-preview.3" />
		<PackageVersion Include="MonoGame.Library.SDL" Version="2.32.10.2" />
		<PackageVersion Include="MonoGame.Library.OpenAL" Version="1.24.3.4" />
	</ItemGroup>
	<Target Name="RestoreDotnetTools" BeforeTargets="CollectPackageReferences">
		<Message Text="Restoring dotnet tools (this might take a while depending on your internet speed and should only happen upon building your project for the first time, or after upgrading MonoGame, or clearing your nuget cache)" Importance="High" />
		<Exec Command="dotnet tool restore" />
	</Target>
</Project>
```

**Comment by dellis1972** [comment]
@Lancelotbronner  can you check the runtimes folder in your output path to see if the win-arm64 folder is present.

**Comment by dellis1972** [comment]
Also sorry, I was on my phone hence the `PackageVersion`...

**Comment by Lancelotbronner** [comment]
They are present in `Z:\Developer\MyGame\bin\Debug\net10.0\runtimes\win-arm64\native`, both `openal.dll` and `SDL2.dll`.

**Comment by dellis1972** [comment]
now I'm stumped. I don't have a windows arm machine to test on. I know the content pipeline won't work yet, but apps should at least run.

**Comment by Lancelotbronner** [comment]
Let me know if there's more troubleshooting I can do! I'll keep trying again from time to time.

**Comment by Lancelotbronner** [comment]
@AristurtleDev Still happens as of 3.8.5 with Visual Studio 2026 on Windows 11 ARM.

**Comment by Lancelotbronner** [comment]
Nevermind that was a different error, this issue is now resolved!
